# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1201, 835)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_run.setGeometry(QtCore.QRect(840, 30, 111, 71))
        self.pushButton_run.setObjectName("pushButton_run")

        self.openFileButton_model = QtWidgets.QPushButton(self.centralwidget)
        self.openFileButton_model.setGeometry(QtCore.QRect(30, 20, 111, 41))
        self.openFileButton_model.setObjectName("openFileButton_model")
        self.openFileButton_image = QtWidgets.QPushButton(self.centralwidget)
        self.openFileButton_image.setGeometry(QtCore.QRect(30, 70, 111, 41))
        self.openFileButton_image.setObjectName("openFileButton_image")

        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1040, 190, 41, 591))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setScaledContents(False)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setScaledContents(False)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setScaledContents(False)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setScaledContents(False)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setTextFormat(QtCore.Qt.AutoText)
        self.label_16.setScaledContents(False)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setTextFormat(QtCore.Qt.AutoText)
        self.label_17.setScaledContents(False)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setTextFormat(QtCore.Qt.AutoText)
        self.label_18.setScaledContents(False)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setTextFormat(QtCore.Qt.AutoText)
        self.label_19.setScaledContents(False)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setScaledContents(False)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_2.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setScaledContents(False)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_2.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_22.setTextFormat(QtCore.Qt.AutoText)
        self.label_22.setScaledContents(False)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_2.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        self.label_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_23.setTextFormat(QtCore.Qt.AutoText)
        self.label_23.setScaledContents(False)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_2.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_24.setTextFormat(QtCore.Qt.AutoText)
        self.label_24.setScaledContents(False)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_2.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        self.label_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_25.setTextFormat(QtCore.Qt.AutoText)
        self.label_25.setScaledContents(False)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        self.label_26.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_26.setTextFormat(QtCore.Qt.AutoText)
        self.label_26.setScaledContents(False)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget)
        self.label_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_27.setTextFormat(QtCore.Qt.AutoText)
        self.label_27.setScaledContents(False)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_2.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget)
        self.label_28.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_28.setTextFormat(QtCore.Qt.AutoText)
        self.label_28.setScaledContents(False)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_2.addWidget(self.label_28)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 130, 1001, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_input = QtWidgets.QLabel(self.layoutWidget1)
        self.label_input.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_input.setAutoFillBackground(False)
        self.label_input.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.label_input.setTextFormat(QtCore.Qt.AutoText)
        self.label_input.setScaledContents(False)
        self.label_input.setWordWrap(False)
        self.label_input.setObjectName("label_input")
        self.horizontalLayout_2.addWidget(self.label_input)
        self.label_groundtruth = QtWidgets.QLabel(self.layoutWidget1)
        self.label_groundtruth.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_groundtruth.setTextFormat(QtCore.Qt.AutoText)
        self.label_groundtruth.setScaledContents(False)
        self.label_groundtruth.setObjectName("label_groundtruth")
        self.horizontalLayout_2.addWidget(self.label_groundtruth)
        self.label_predict = QtWidgets.QLabel(self.layoutWidget1)
        self.label_predict.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_predict.setTextFormat(QtCore.Qt.AutoText)
        self.label_predict.setScaledContents(False)
        self.label_predict.setObjectName("label_predict")
        self.horizontalLayout_2.addWidget(self.label_predict)
        self.label_output = QtWidgets.QLabel(self.layoutWidget1)
        self.label_output.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_output.setTextFormat(QtCore.Qt.AutoText)
        self.label_output.setScaledContents(False)
        self.label_output.setObjectName("label_output")
        self.horizontalLayout_2.addWidget(self.label_output)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(1040, 110, 141, 61))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_aug = QtWidgets.QLabel(self.layoutWidget2)
        self.label_aug.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_aug.setTextFormat(QtCore.Qt.AutoText)
        self.label_aug.setScaledContents(False)
        self.label_aug.setObjectName("label_aug")
        self.verticalLayout_3.addWidget(self.label_aug)
        self.textBrowser_aug = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.textBrowser_aug.setObjectName("textBrowser_aug")
        self.verticalLayout_3.addWidget(self.textBrowser_aug)
        self.textBrowser_model = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_model.setGeometry(QtCore.QRect(150, 20, 621, 41))
        self.textBrowser_model.setObjectName("textBrowser_model")
        self.textBrowser_image = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_image.setGeometry(QtCore.QRect(150, 70, 621, 41))
        self.textBrowser_image.setObjectName("textBrowser_image")
        self.label_inputimage = QtWidgets.QLabel(self.centralwidget)
        self.label_inputimage.setGeometry(QtCore.QRect(10, 180, 250, 600))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_inputimage.setFont(font)
        self.label_inputimage.setAutoFillBackground(True)
        self.label_inputimage.setText("")
        self.label_inputimage.setObjectName("label_inputimage")
        self.label_groundtruthimage = QtWidgets.QLabel(self.centralwidget)
        self.label_groundtruthimage.setGeometry(QtCore.QRect(260, 180, 250, 600))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_groundtruthimage.setFont(font)
        self.label_groundtruthimage.setAutoFillBackground(True)
        self.label_groundtruthimage.setText("")
        self.label_groundtruthimage.setObjectName("label_groundtruthimage")
        self.label_predictimage = QtWidgets.QLabel(self.centralwidget)
        self.label_predictimage.setGeometry(QtCore.QRect(510, 180, 250, 600))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_predictimage.setFont(font)
        self.label_predictimage.setAutoFillBackground(True)
        self.label_predictimage.setMidLineWidth(0)
        self.label_predictimage.setText("")
        self.label_predictimage.setWordWrap(False)
        self.label_predictimage.setObjectName("label_predictimage")
        self.label_outputimage = QtWidgets.QLabel(self.centralwidget)
        self.label_outputimage.setGeometry(QtCore.QRect(760, 180, 250, 600))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_outputimage.setFont(font)
        self.label_outputimage.setAutoFillBackground(True)
        self.label_outputimage.setMidLineWidth(0)
        self.label_outputimage.setText("")
        self.label_outputimage.setWordWrap(False)
        self.label_outputimage.setObjectName("label_outputimage")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(1080, 190, 101, 591))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.verticalLayout.addWidget(self.textBrowser_4)
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.verticalLayout.addWidget(self.textBrowser_5)
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.verticalLayout.addWidget(self.textBrowser_6)
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.verticalLayout.addWidget(self.textBrowser_7)
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.verticalLayout.addWidget(self.textBrowser_8)
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.verticalLayout.addWidget(self.textBrowser_9)
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.verticalLayout.addWidget(self.textBrowser_10)
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.verticalLayout.addWidget(self.textBrowser_11)
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.verticalLayout.addWidget(self.textBrowser_12)
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.verticalLayout.addWidget(self.textBrowser_13)
        self.textBrowser_14 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.verticalLayout.addWidget(self.textBrowser_14)
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.verticalLayout.addWidget(self.textBrowser_15)
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.verticalLayout.addWidget(self.textBrowser_16)
        self.textBrowser_17 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_17.setObjectName("textBrowser_17")
        self.verticalLayout.addWidget(self.textBrowser_17)
        self.textBrowser_18 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_18.setObjectName("textBrowser_18")
        self.verticalLayout.addWidget(self.textBrowser_18)
        self.textBrowser_19 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_19.setObjectName("textBrowser_19")
        self.verticalLayout.addWidget(self.textBrowser_19)
        self.textBrowser_20 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_20.setObjectName("textBrowser_20")
        self.verticalLayout.addWidget(self.textBrowser_20)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1201, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "影響處理Demo_張軍斌_P78083025"))
        self.pushButton_run.setText(_translate("MainWindow", "Run"))
        self.openFileButton_model.setText(_translate("MainWindow", "Model"))
        self.openFileButton_image.setText(_translate("MainWindow", "Image"))
        self.label_12.setText(_translate("MainWindow", "V0"))
        self.label_13.setText(_translate("MainWindow", "V1"))
        self.label_14.setText(_translate("MainWindow", "V2"))
        self.label_15.setText(_translate("MainWindow", "V3"))
        self.label_16.setText(_translate("MainWindow", "V4"))
        self.label_17.setText(_translate("MainWindow", "V5"))
        self.label_18.setText(_translate("MainWindow", "V6"))
        self.label_19.setText(_translate("MainWindow", "V7"))
        self.label_20.setText(_translate("MainWindow", "V8"))
        self.label_21.setText(_translate("MainWindow", "V9"))
        self.label_22.setText(_translate("MainWindow", "V10"))
        self.label_23.setText(_translate("MainWindow", "V11"))
        self.label_24.setText(_translate("MainWindow", "V12"))
        self.label_25.setText(_translate("MainWindow", "V13"))
        self.label_26.setText(_translate("MainWindow", "V14"))
        self.label_27.setText(_translate("MainWindow", "V15"))
        self.label_28.setText(_translate("MainWindow", "V16"))
        self.label_input.setText(_translate("MainWindow", "Input"))
        self.label_groundtruth.setText(_translate("MainWindow", "Ground truth"))
        self.label_predict.setText(_translate("MainWindow", "Predict"))
        self.label_output.setText(_translate("MainWindow", "Output"))
        self.label_aug.setText(_translate("MainWindow", "AUG"))

